- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /home/ubuntu/project/backend
    state: directory
    mode: '0755'

- name: "copy folder "
  become: true
  copy:
    #src: /root/project/backend/dist
    src: /root/project/backend/artifact.tar.gz
    #src: /root/project/
    dest: /home/ubuntu/project/backend

- name: "untar folder "
  become: true
  ansible.builtin.unarchive:
    #src: /root/project/backend/dist
    src: /home/ubuntu/project/backend/artifact.tar.gz
    #src: /root/project/
    dest: /home/ubuntu/project/backend/
    remote_src: yes

- name: "start server"
  become: true
  command: |
    npm install
    pm2 stop default
    pm2 start npm -- start
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    - TYPEORM_MIGRATIONS_DIR: "./migrations"
    - TYPEORM_MIGRATIONS: "./migrations/*.js"
    - TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"